/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>



int main(void)
{
	uint32_t * RCC= (uint32_t*) 0x40023800;
	uint32_t * RCC_AHB1 =RCC +12;
	uint32_t * GPIOD= 0x40020C00;
	uint32_t * GPIOD_MODER= GPIOD + 0;
	uint32_t * GPIOD_ODR= GPIOD + 5;
	uint32_t * GPIOA= 0x40020000 ;
	uint32_t * GPIOA_MODER= GPIOA + 0;
	uint32_t * GPIOA_IDR= GPIOA + 4;
	uint32_t * GPIOA_PUPDR= GPIOA + 3;

	*RCC_AHB1 |=1<<3; //Set GPIOD clock
	*RCC_AHB1 |=1<<0; //Set GPIOA clock
	* GPIOD_MODER &=~(5<<24);
	* GPIOD_MODER |=0x05<<24 ;// Set  PD13 and PD12 to output
	* GPIOA_MODER &=~(1<<0) ;// Set  PA0 to input
	* GPIOA_PUPDR &=~(3<<0);
	* GPIOA_PUPDR |=(2<<0);


	while(1)
	{
		uint32_t j= * GPIOA_IDR & 1<<0;
		if (j==0)
		{
			* GPIOD_ODR	|= 1<<13  ; //Set PD13 to high
			* GPIOD_ODR &= ~(1<<12) ;//Set PD12 to low
			for (uint32_t i=0; i<1000000; i++);
			* GPIOD_ODR &= ~(1<<13) ;//Set PD13 to low
			* GPIOD_ODR	|= 1<<12  ; //Set PD12 to high
			for (uint32_t i=0; i<1000000; i++);
		}
		else
		{
			* GPIOD_ODR	|= 1<<13  ; //Set PD13 to high
			* GPIOD_ODR &= ~(1<<12) ;//Set PD12 to low
			for (uint32_t i=0; i<100000; i++);
			* GPIOD_ODR &= ~(1<<13) ;//Set PD13 to low
			* GPIOD_ODR	|= 1<<12  ; //Set PD12 to high
			for (uint32_t i=0; i<100000; i++);
		}

	}

}
